### ISSUE TITLE
Class 'XPack\Security\Endpoints\Authenticate' not found

### ISSUE THREAD

**Issue by VincentMolinie** [elastic/elasticsearch-x-pack-php#2]
Hi,

When I try to authenticate I get this error:
`Class 'XPack\Security\Endpoints\Authenticate' not found`

My code:
```
$client = ClientBuilder::create()
            ->registerNamespace(XPack::Security())
            ->setHosts(["https://localhost:9200"])
            ->build();
$client->security()->authenticate(['username' => 'elasticsearch', 'password' => 'changeme']);
```

**Comment by JamesB797** [comment]
The XPack composer.json is using PSR4 for its autoloads, which is case-sensitive on directory and namespace names.

In the repo, the `endpoints` directory is lowercase, while the namespace `XPack\Security\Endpoints\Authenticate` has uppercase `Endpoints`. I know that if you rename the endpoints directory to Endpoints in the watcher namespace it works, so I assume that would work for the security endpoint as well.

OLD/WRONG: A reasonable solution: it seems as though newer versions of composer (1.4.2 in this case) don't obey PSR4 exactly, and load the lowercase endpoints directory for the Endpoints namespace anyway, so you could try updating composer.
EDIT: Actually it's the newest versions of composer that follow PSR4 exactly, 1.4.2 and older recognize endpoints as Endpoints.

If you can't update composer, you could try adding a PSR4 rule to your own composer.json that autoloads the endpoints directory in each namespace you need to the right namespace prefix.

In my opinion, the best option would be for the endpoints directories in this repo to be renamed to the uppercase version, unless there's a compelling reason for it to be lowercase (I doubt it).

**Comment by polyfractal** [comment]
@JamesB797 Oh, interesting... I didn't realize that different versions of composer were case sensitive/insensitive.

Renaming the endpoints directory should be fine, I'll make the change and tag a new version soon.  Thanks for tracking this down!

**Comment by ezimuel** [comment]
Outdated issue. If still relevant please open an issue to [elastic/elasticsearch-php](https://github.com/elastic/elasticsearch-php).
