### ISSUE TITLE
Call to undefined method XPack\Watcher\Endpoints\PutWatch::resultOrFuture()

### ISSUE THREAD

**Issue by parallelaus** [elastic/elasticsearch-x-pack-php#3]
I have Elasticsearch SDK v5.0.0 and XPack v5.0.0 installed.

When I make a putWatch call, I get the error above. I have traced the error and the call to resultOrFuture() is in XPack\Watcher\WatcherNamespace::PutWatch method.

From what I can see resultOrFuture is a member of Elasticsearch\Transport and not of any of the end point classes (e.g. PutWatch)

The watch is actually created in Elastic since I can get the watcher with Dev tools in Kibana. So there is no problem with the connection to the Elastic cluster. It literally fails on the last line of the putWatch function. 

Any ideas?

**Comment by polyfractal** [comment]
Hi @parallelaus, sorry for the delay... for some reason my notifications of this repo became disabled and I never saw your ticket :(

`resultOrFuture` is indeed part of `Elasticsearch\Transport`, but it should be getting imported.  The XPack namespaces extend `Elasticsearch\Namespaces\AbstractNamespace`, and `AbstractNamespace` has a reference to the transport internally (https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Namespaces/AbstractNamespace.php#L20).

Can you show your `composer.json` and initialization code (where you include the `autoloader`, initialize the client, etc)?

**Comment by JamesB797** [comment]
This could be related to https://github.com/elastic/elasticsearch-x-pack-php/issues/2 . If composer is the newest version, it won't autoload the `Endpoints` namespace because the directory `endpoints`, and so it won't find PutWatch or any method it's supposed to have.

**Comment by eugenbg** [comment]
hi @polyfractal 

i ran into the same issue

```
public function getRole($params)
    {
        $name = $this->extractArgument($params, 'name');

        $endpoint = new Endpoints\GetRole();
        $endpoint->setName($name)
            ->setParams($params);
        $response = $this->performRequest($endpoint);
        return $endpoint->resultOrFuture($response);
    }
```

the namespace calls $endpoint->resultOrFuture($response);
and Endpoint does not have a method resultOrFuture, nor does its parent

could you please explain how it's supposed to use Elasticsearch\Transport to call the method?

**Comment by eugenbg** [comment]
oops sorry i must have installed some other version with composer somehow

**Comment by ezimuel** [comment]
Outdated issue. If still relevant please open an issue to [elastic/elasticsearch-php](https://github.com/elastic/elasticsearch-php).
