### ISSUE TITLE
X-pack Jobs

### ISSUE THREAD

**Issue by rajcscw** [elastic/elasticsearch-x-pack-php#4]
Does it have support for creating and running X-pack ML jobs? I see that there is ML namespace, it would be cool if there is support in this SDK.

**Comment by david-vde** [comment]
I agree with rajcscw.

I'm looking for an easy way to trigger Job report generation using the client

Currently hard to do

**Comment by ezimuel** [comment]
Outdated issue. If still relevant please open an issue to [elastic/elasticsearch-php](https://github.com/elastic/elasticsearch-php).
