### ISSUE TITLE
Quetion about compatibility

### ISSUE THREAD

**Issue by NayrMorales** [elastic/elasticsearch-x-pack-php#6]
Is this package support newer version of elasticsearch? 
I am currently using php client elasticsearch version 6.0 . I have been search around the corner but there is no similar package that I am looking for like this repo. Any solution?

**Comment by ezimuel** [comment]
The support of XPack has been moved in [elastic/elasticsearch-php](https://github.com/elastic/elasticsearch-php) since [7.7.0](https://github.com/elastic/elasticsearch-php/releases/tag/v7.7.0). I'm working to backport it also in 6.x with a `6.8.0` release.
